version: '3.8'

services:
  grafana:
    image: ${GRAFANA_IMAGE}:${GRAFANA_TAG}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./../configs/grafana/provisioning/:/etc/grafana/provisioning/
      - ./../configs/grafana/grafana.ini:/etc/grafana/grafana.ini
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 1m
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.backend=grafana"
        - "traefik.enable=true"      
        - "traefik.docker.network=${DOCKER_FRONT_NETWORK}"
        - "traefik.port=3000"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.auth.basic=${AUTH_USER}:${AUTH_PASSWORD}"
        - "traefik.frontend.rule=Host:grafana.${SUBDOMAIN}"
        - "traefik.frontend.headers.customResponseHeaders=X-XSS-Protection: 1; mode=block"        
      restart_policy:
        condition: on-failure
    networks:
      - kargo-front-network
      - kargo-back-network

volumes:
  grafana_data: {}

networks:
  kargo-front-network:
    name: ${DOCKER_FRONT_NETWORK}
    external: true
  kargo-back-network:
    name: ${DOCKER_BACK_NETWORK}
    external: true
